export enum EDroppableType {
  SCENARIO = 'SCENARIO',
  OPERATION = 'OPERATION',
}

export enum EDroppableId {
  SCENARIO_LIST = 'SCENARIO_LIST',
  OPERATION_LIST = 'OPERATION_LIST',
  SCENARIO_TABLE = 'SCENARIO_TABLE',
}
